language: ruby
rvm:
- 2.2
before_script:
- export TZ=Pacific/Auckland
branches:
  only:
  - master
install: gem install jekyll && gem install jekyll-paginate && gem install jekyll-email-protect && gem install jekyll-sitemap
script: JEKYLL_ENV=production jekyll build
deploy:
  provider: s3
  bucket: bhavik.io
  skip_cleanup: true
  region: us-east-1
  local_dir: _site
  access_key_id:
    secure: "DjuVoWpr7vctyBP9003PSRDbbivnkIcOTRJmsufnsjZOYRo4sLwpC6Utr15jWVYPi/XuONySksQKCKbNwVghhxQJjjpUMM+UoRiSBwYcW+KsbAfIY/GzYVS3ElaG4k969mZbnwzxYvj2N/n2Co2sOLdeB7WhVoPRRBFD0cGspcRpNu7IjTKkM2xlQ/mdw26MiX9Do3K4dWAkR3ytXJEOuFfm9r2A1pJVR3914bDdBhQrq15+5tbo4CDdFHhfaLfd61VABEweD9PALd7n+05qfMmbd6aEKC3MvahZQjmSwe0vWM8MyZGFXnLm8unIR0gqbN5daz7IPulbJF8Aq3G+oqkDCexjS/hrmH9i7JywVX4z23NvxeDlmqdjS1TN3BbkQUmqxGk2K2MQ9GjEa9jHYRW+Yb4zz19QORipfKDVZtvcwoAF6wvNMcPSacuoQIaZhC6LGtTdaQGRNQ9sldcjGkpH5eYj38nckBV4dCTC8JAVbZid/PbgGfSUDAXWxh5EAShyjEZUxklO0ac748nNaqI/wtUnlIqgxI7H3FsbPnA22bG4M7N1gQ15I5ikayHRuHMJ/4/TXLvzgas26AsLghqE4GUuWO4VZlbtVVJ4RxcgKQ/qRwc53BZtoKE7cgEHxsdS67Q9hM0LwYcGuk0R2H9tcGLQQGGWIxayRgtzSZo="
  secret_access_key:
    secure: "sdWV2+M1kOs5G4Ptl1dAew/snu6aFDRhGH9LAbUEO2kNRzOBu9jWwoWcb6QcNZjNCrilupzKmsYRnLZQ0AvD89CeQEcLHGwQPvnjC90olLtv0Y8L5sRsSXCq3dc+uIido0QlNrtN18BXwp2N/sMXdRMEoObyNZbrTqGQmC5B0TFBqeOPEhPpa135ZNj6WquV+KZPHoHMnQGyUOtCMoc79UIRlBVMJlL0BIJRHfgb/OnkvG3EUgKlBLI2T8zNV8I3DRvYd1pW9h44jvd5Lh+K1Spsbzw8ZOMKE03ak0BL4eFfhqQN0pRuVLj425kLIv4N845sjbDj9bRoi4ktcxQqC/qjwrHy2Gipn971rWrip8bRFNCzpf0bsSBOJx+BYiDGvkA3+m1+dDKH+k8LglmIG/11bdL7e3UctjxVTgggSdhlQBPLquEXSNu9KVrCUY7nvTfkLSAR9x0JBts5rQvjG7j8vyJm6GGxQw2DzywVJbYj698VfKCofPU8WcvEWR3mMUPPG4g0fQ8Ku+1H4u9QV6AtNLB4oJDahMVKwzNXeQHBei3shQoflOamOIKP1sn2xaUaxnTGsUaiK1m2KcaJjJOI5kFGNyxfapBCqkO8quc91/eoMK2EmsmeoqGCt6XjbyfpWbrUtZT3IzbHchiq7qUdHKYSsZUAu9sw0c0GedQ="
