# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Gems
plugins: [jekyll-paginate, jekyll-email-protect]

# Site settings
title: Bhavik Kumar
email: contact@bhavik.io
description: > # this means to ignore newlines until "baseurl:"
  <b>Bhavik</b> is a software engineer. He started his career by
  working for one of New Zealand's largest IT consultancies. Now
  he works for a large FMCG co-operative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bhavik.io" # the base hostname & protocol for your site
twitter_username: BhavikKumarNZ
github_username:  bhavikkumar
google_analytics: UA-78148514-1

# Build settings
markdown: kramdown

# Pagination settings
paginate: 10

sass:
  style: compressed

includes:
- keybase.txt

disqus: bhavik-1

exclude:
  - README.md
  - LICENSE

# Headers
webrick:
  headers:
    Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' www.google-analytics.com *.disqus.com *.disquscdn.com disqus.com; style-src 'self' fonts.googleapis.com *.disqus.com *.disquscdn.com; img-src 'self' www.google-analytics.com *.disqus.com *.disquscdn.com; frame-src 'self' disqus.com; font-src 'self' fonts.googleapis.com fonts.gstatic.com"
    X-Frame-Options: "x-frame-options: SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"
