# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bhavik Kumar
email: contact@bhavik.io
description: > # this means to ignore newlines until "baseurl:"
  <b>Bhavik</b> is a software engineer. He started his career by
  working for one of New Zealand's largest IT consultancies. Now
  he works for a leading payments company building new digital 
  products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bhavik.io" # the base hostname & protocol for your site
# twitter_username: bhavikkumar
github_username:  bhavikkumar

# Build settings
markdown: kramdown

google_analytics: UA-78148514-1